### ISSUE TITLE
Light brightness change service not properly implemented

### ISSUE THREAD

**Issue by 0nikola1** [CoolKit-Technologies/ha-addon#101]
Calling this service works:
```
service: light.turn_on
data:
  brightness_pct: 11
target:
  entity_id: id
```

This doesn't:
```
service: light.turn_on
data:
  brightness: 36
target:
  entity_id: id
```
