### ISSUE TITLE
After upgrading to 1.4.3 the switches cannot be used in automations because they are not listed as devices.

### ISSUE THREAD

**Issue by gituletz** [CoolKit-Technologies/ha-addon#134]
After upgrading to 1.4.3 the switches cannot be used in automation because they are not listed as devices. The Sonoff switches are listed only as entities.
There is an associated notification with the sonoff switches  mentioning they cannot be managed because they don't have a unique ID:

 This entity ('switch.10010ee5c2') does not have a unique ID, therefore its settings cannot be managed from the UI. See the [documentation](https://www.home-assistant.io/faq/unique_id) for more detail.

**Comment by redelacruz** [comment]
Can confirm. I really hope everything can get a unique ID.

There is a workaround, though. You can use services in automations to accomplish what you want. It's a lot more roundabout, but it works.

Example code:
```
mode: single
trigger:
  - platform: sun
    event: sunrise
    offset: 0
  - platform: sun
    event: sunset
    offset: 0
action:
  - if:
      - condition: sun
        after: sunrise
        before: sunset
    then:
      - service: switch.turn_off
        target:
          entity_id: switch.10010ee5c2
    else:
      - service: switch.turn_on
        target:
          entity_id: switch.10010ee5c2
```
