### ISSUE TITLE
iFan 03 light control

### ISSUE THREAD

**Issue by joluas** [CoolKit-Technologies/ha-addon#57]
This is an issue that is not covered on the readme but I was able to solve it.

If you have an iFan03, the settings available on https://github.com/CoolKit-Technologies/ha-addon/blob/master/eWeLink_Smart_Home/README.md are missing one configuration so that you are able to control the light from the Lovelace dashboard.

Add this to configuration.yaml:
```
light:            
  - platform: template
    lights:
      ewelink_virtual_fan:
        turn_on:
          service: light.turn_on
        turn_off:
          service: light.turn_off
```

Without this configuration you get the error: 
**Failed to call service light/turn.on. Service not found**

Hope that this helps someone so that they avoid the 3 days of troubleshooting that I performed.
